language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wafahmi/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true wafahmi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-525861701306"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



